// Enhanced Software Product Builder
// Generates comprehensive PRDs and professional development prompts

export interface SoftwareProductContext {
  // From UVZ Research
  industry?: string;
  niche?: string;
  uvz?: string;
  targetAudience?: string;
  competitorWeaknesses?: string;
  marketGap?: string;
  
  // Product Basics
  name: string;
  tagline?: string;
  description?: string;
  toolType: string;
  problemSolved: string;
  
  // Features
  coreFeatures: string[];
  differentiators?: string[];
  
  // Technical
  techStack?: string[];
  platform?: string;
}

export interface PRDSection {
  title: string;
  content: string;
}

// Generate a comprehensive Product Requirements Document
export function generatePRD(context: SoftwareProductContext): string {
  const sections: PRDSection[] = [
    generateExecutiveSummary(context),
    generateProblemStatement(context),
    generateSolutionOverview(context),
    generateTargetUsers(context),
    generateFunctionalRequirements(context),
    generateNonFunctionalRequirements(context),
    generateTechnicalArchitecture(context),
    generateSecurityRequirements(context),
    generateUIUXRequirements(context),
    generateMVPScope(context),
    generateSuccessMetrics(context),
    generateRisksAndMitigations(context),
  ];

  return `# Product Requirements Document (PRD)
# ${context.name}

**Document Version:** 1.0
**Last Updated:** ${new Date().toLocaleDateString()}
**Status:** Draft

---

${sections.map(s => `## ${s.title}\n\n${s.content}`).join('\n\n---\n\n')}

---

*Generated by ManyMarkets Product Builder*
`;
}

function generateExecutiveSummary(ctx: SoftwareProductContext): PRDSection {
  return {
    title: '1. Executive Summary',
    content: `### Product Vision
**${ctx.name}** is a ${ctx.toolType.toLowerCase()} designed to ${ctx.problemSolved.toLowerCase()}.

${ctx.tagline ? `**Tagline:** "${ctx.tagline}"` : ''}

### Market Opportunity
${ctx.marketGap ? `This product addresses a clear market gap: ${ctx.marketGap}` : 'This product addresses an underserved need in the market.'}

${ctx.uvz ? `### Unique Value Zone (UVZ)
${ctx.uvz}

This UVZ positions us uniquely against competitors by focusing on what they're missing.` : ''}

### Key Differentiators
${ctx.differentiators?.length ? ctx.differentiators.map(d => `- ${d}`).join('\n') : `- Focused solution for a specific problem
- Modern, intuitive user experience
- Built with security and scalability in mind`}
`
  };
}

function generateProblemStatement(ctx: SoftwareProductContext): PRDSection {
  return {
    title: '2. Problem Statement',
    content: `### The Problem
${ctx.problemSolved}

### Current Solutions & Their Limitations
${ctx.competitorWeaknesses ? ctx.competitorWeaknesses : `Current solutions in the market are:
- Too complex for the average user
- Missing key features that users need
- Expensive or poorly supported
- Not designed with modern UX principles`}

### Impact on Users
Users currently experience:
- **Time waste:** Hours spent on inefficient workarounds
- **Frustration:** Dealing with clunky interfaces or missing features
- **Cost:** Paying for bloated solutions they don't fully utilize
- **Risk:** Security vulnerabilities in outdated tools

### Why Now?
The market is ready for this solution because:
1. Technology has matured to make this achievable
2. User expectations have evolved
3. The problem has become more acute with ${ctx.industry || 'industry'} growth
`
  };
}

function generateSolutionOverview(ctx: SoftwareProductContext): PRDSection {
  return {
    title: '3. Solution Overview',
    content: `### Product Description
${ctx.description || `${ctx.name} provides a streamlined, modern solution to ${ctx.problemSolved.toLowerCase()}.`}

### How It Works
1. **User enters the tool** → Clean, intuitive onboarding
2. **Core workflow** → Accomplish their primary task efficiently
3. **Value delivery** → See immediate results and value
4. **Return & expand** → Build habits and explore advanced features

### Core Value Proposition
"${ctx.name} is the ${ctx.toolType.toLowerCase()} that lets you ${ctx.problemSolved.split('.')[0].toLowerCase()}, without the complexity."

### Key Benefits
- **Speed:** Get results faster than any alternative
- **Simplicity:** No learning curve, intuitive design
- **Reliability:** Works consistently, every time
- **Security:** Built with modern security best practices
`
  };
}

function generateTargetUsers(ctx: SoftwareProductContext): PRDSection {
  return {
    title: '4. Target Users & Personas',
    content: `### Primary Target Audience
${ctx.targetAudience || 'Professionals and individuals who need this solution'}

### User Persona: Primary User
**Name:** Alex (Represents our core user)
**Role:** ${ctx.niche ? `Professional in ${ctx.niche}` : 'Knowledge worker'}
**Goals:**
- Complete their task quickly and efficiently
- Reduce friction in their workflow
- Have confidence in the tool's reliability

**Pain Points:**
- Current solutions are too complex
- Wasting time on manual processes
- Worried about security/privacy

**Success Criteria:**
- Can achieve their goal in under 5 minutes
- Feels confident using the tool immediately
- Would recommend to colleagues

### User Journey Map
\`\`\`
Awareness → Interest → Trial → First Value → Regular Use → Advocate
   ↓          ↓         ↓          ↓            ↓           ↓
  Sees ad   Visits   Creates    Completes    Uses 3x     Refers
  or ref    site    account    first task    weekly     friends
\`\`\`
`
  };
}

function generateFunctionalRequirements(ctx: SoftwareProductContext): PRDSection {
  const features = ctx.coreFeatures || [
    'User authentication',
    'Core functionality',
    'Data management',
    'Settings/preferences'
  ];

  return {
    title: '5. Functional Requirements',
    content: `### Core Features (MVP)

${features.map((f, i) => `#### F${i + 1}: ${f}
**Priority:** ${i < 3 ? 'P0 - Must Have' : i < 5 ? 'P1 - Should Have' : 'P2 - Nice to Have'}
**User Story:** As a user, I want to ${f.toLowerCase()} so that I can accomplish my goal.
**Acceptance Criteria:**
- Feature is fully functional
- Works on all supported platforms
- Has appropriate error handling
- Includes loading states
- Passes accessibility checks
`).join('\n')}

### Feature Prioritization Matrix
| Feature | Impact | Effort | Priority |
|---------|--------|--------|----------|
${features.slice(0, 5).map((f, i) => `| ${f} | High | ${i < 2 ? 'Medium' : 'High'} | P${i < 3 ? '0' : '1'} |`).join('\n')}
`
  };
}

function generateNonFunctionalRequirements(ctx: SoftwareProductContext): PRDSection {
  return {
    title: '6. Non-Functional Requirements',
    content: `### Performance Requirements
- **Page Load Time:** < 2 seconds on 3G connection
- **Time to Interactive:** < 3 seconds
- **API Response Time:** < 200ms (p95)
- **Uptime:** 99.9% availability

### Scalability Requirements
- Support 10,000+ concurrent users
- Handle 1M+ API requests per day
- Database can scale to 100GB+ data

### Accessibility Requirements
- WCAG 2.1 AA compliance
- Keyboard navigation support
- Screen reader compatibility
- Color contrast ratios ≥ 4.5:1

### Browser/Platform Support
${ctx.toolType.includes('Extension') ? `
- Chrome 90+
- Firefox 88+
- Edge 90+
- Safari 14+ (if applicable)
` : ctx.toolType.includes('Mobile') || ctx.toolType.includes('App') ? `
- iOS 14+
- Android 10+
- Progressive Web App support
` : `
- Chrome 90+
- Firefox 88+
- Safari 14+
- Edge 90+
- Mobile responsive design
`}

### Localization
- Initial launch: English only
- Architecture supports future i18n
- Right-to-left (RTL) layout support planned
`
  };
}

function generateTechnicalArchitecture(ctx: SoftwareProductContext): PRDSection {
  const techStack = ctx.techStack || getDefaultTechStack(ctx.toolType);
  
  return {
    title: '7. Technical Architecture',
    content: `### Recommended Tech Stack
${techStack.map(t => `- **${t}**`).join('\n')}

### Architecture Overview
\`\`\`
┌─────────────────────────────────────────────────────────────┐
│                        CLIENT LAYER                          │
│  ┌─────────────┐  ┌─────────────┐  ┌─────────────────────┐  │
│  │   Web App   │  │   Mobile    │  │  ${ctx.toolType.includes('Extension') ? 'Extension' : 'PWA'}      │  │
│  │  (Next.js)  │  │   (React    │  │  (${ctx.toolType.includes('Extension') ? 'Manifest V3' : 'Service Worker'})  │  │
│  └─────────────┘  │   Native)   │  └─────────────────────┘  │
│                   └─────────────┘                            │
└─────────────────────────────────────────────────────────────┘
                              │
                              ▼
┌─────────────────────────────────────────────────────────────┐
│                        API LAYER                             │
│  ┌─────────────────────────────────────────────────────┐    │
│  │              API Gateway / Load Balancer              │    │
│  └─────────────────────────────────────────────────────┘    │
│                              │                               │
│  ┌──────────────┐  ┌──────────────┐  ┌──────────────────┐   │
│  │ Auth Service │  │  Core API    │  │  Background Jobs  │   │
│  │  (Sessions)  │  │  (REST/tRPC) │  │   (Queue/Cron)   │   │
│  └──────────────┘  └──────────────┘  └──────────────────┘   │
└─────────────────────────────────────────────────────────────┘
                              │
                              ▼
┌─────────────────────────────────────────────────────────────┐
│                       DATA LAYER                             │
│  ┌──────────────┐  ┌──────────────┐  ┌──────────────────┐   │
│  │  PostgreSQL  │  │    Redis     │  │   File Storage   │   │
│  │  (Primary)   │  │   (Cache)    │  │   (S3/R2/etc)   │   │
│  └──────────────┘  └──────────────┘  └──────────────────┘   │
└─────────────────────────────────────────────────────────────┘
\`\`\`

### Data Model (Core Entities)
\`\`\`sql
-- Users table
CREATE TABLE users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255),
  name VARCHAR(255),
  avatar_url TEXT,
  role VARCHAR(50) DEFAULT 'user',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add your domain-specific tables here
-- Example for a typical SaaS:
CREATE TABLE projects (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES users(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  data JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
\`\`\`

### API Design Principles
- RESTful endpoints with consistent naming
- JSON:API or similar response format
- Proper HTTP status codes
- Pagination, filtering, sorting support
- Rate limiting per user/tier
- Comprehensive error messages
`
  };
}

function generateSecurityRequirements(ctx: SoftwareProductContext): PRDSection {
  return {
    title: '8. Security Requirements',
    content: `### Authentication & Authorization
- **Primary Auth:** Email/password with secure hashing (bcrypt, cost 12)
- **Session Management:** 
  - JWT tokens with short expiry (15 min access, 7 day refresh)
  - Secure, httpOnly, sameSite cookies
  - Token rotation on refresh
- **OAuth Support:** Google, GitHub (optional based on user base)
- **MFA:** TOTP-based 2FA for sensitive accounts

### Data Security
- **Encryption at Rest:** AES-256 for sensitive data
- **Encryption in Transit:** TLS 1.3 mandatory
- **PII Handling:**
  - Minimize collection
  - Hash/encrypt sensitive fields
  - Audit access logs
- **API Keys:** 
  - SHA-256 hashed storage
  - Prefix for identification (e.g., \`mm_live_\`)
  - Scoped permissions

### Application Security
- **Input Validation:** 
  - Server-side validation on ALL inputs
  - Use Zod/Yup schemas
  - Sanitize before database/display
- **SQL Injection:** Parameterized queries only (ORM/query builder)
- **XSS Prevention:** 
  - Content Security Policy headers
  - Output encoding
  - No \`dangerouslySetInnerHTML\` without sanitization
- **CSRF Protection:** Token-based for all state-changing operations
- **Rate Limiting:**
  - Login: 5 attempts per 15 min
  - API: 100 req/min (free), 1000 req/min (paid)
  - Signup: 3 per hour per IP

### Infrastructure Security
- **Headers:** Implement all security headers
  \`\`\`
  Strict-Transport-Security: max-age=31536000; includeSubDomains
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY
  Content-Security-Policy: default-src 'self'
  Referrer-Policy: strict-origin-when-cross-origin
  \`\`\`
- **Dependencies:** 
  - Weekly automated security scans
  - Keep dependencies updated
  - Use lockfiles
- **Secrets Management:**
  - Environment variables only
  - Never commit secrets
  - Use secret managers in production

### Compliance Considerations
- GDPR: Data export, deletion, consent
- CCPA: California privacy rights
- SOC 2: If targeting enterprise
`
  };
}

function generateUIUXRequirements(ctx: SoftwareProductContext): PRDSection {
  return {
    title: '9. UI/UX Requirements',
    content: `### Design Philosophy
**"Professional, not gimmicky. Functional, not flashy."**

The design should feel:
- **Clean:** Generous whitespace, clear hierarchy
- **Professional:** Appropriate for business use
- **Trustworthy:** Inspires confidence in the product
- **Efficient:** Every element serves a purpose

### Design System

#### Colors
\`\`\`
Primary:     #0066FF (Action blue - trustworthy, professional)
Secondary:   #1A1A2E (Deep navy - sophisticated)
Success:     #10B981 (Green - confirmation)
Warning:     #F59E0B (Amber - caution)
Error:       #EF4444 (Red - errors)
Background:  #FAFAFA (Off-white - easy on eyes)
Surface:     #FFFFFF (White - cards, modals)
Text:        #1F2937 (Dark gray - readable)
Muted:       #6B7280 (Gray - secondary text)
\`\`\`

#### Typography
\`\`\`
Font Family: Inter (or system-ui fallback stack)
Headings:    600-700 weight
Body:        400 weight
Sizes:       
  - xs: 12px   - sm: 14px   - base: 16px
  - lg: 18px   - xl: 20px   - 2xl: 24px
  - 3xl: 30px  - 4xl: 36px
Line Height: 1.5 for body, 1.2 for headings
\`\`\`

#### Spacing (8px base unit)
\`\`\`
xs: 4px    sm: 8px    md: 16px   lg: 24px   xl: 32px   2xl: 48px
\`\`\`

#### Component Patterns
- **Buttons:** 
  - Primary: Filled, rounded-lg (8px), subtle shadow
  - Secondary: Outlined, same radius
  - Ghost: No background, text only
  - States: Default → Hover (slight darken) → Active (slight inset) → Disabled (50% opacity)

- **Inputs:**
  - Border: 1px solid #E5E7EB
  - Focus: Ring-2 primary color
  - Error: Red border, error message below
  - Height: 40px standard, 48px large

- **Cards:**
  - Background: White
  - Border: 1px solid #E5E7EB OR subtle shadow
  - Radius: 12px
  - Padding: 24px

### Key Screens

1. **Onboarding/Login**
   - Clean, single-column form
   - Social auth options (if applicable)
   - Progress indicator for multi-step

2. **Dashboard/Home**
   - Clear primary action
   - Quick stats (if relevant)
   - Recent activity

3. **Core Feature Screen**
   - Focused on primary task
   - Minimal distractions
   - Clear feedback on actions

4. **Settings**
   - Organized sections
   - Toggle switches for on/off
   - Confirmation for destructive actions

### Interaction Patterns
- **Loading:** Skeleton screens > Spinners
- **Empty States:** Helpful illustrations + CTA
- **Errors:** Inline + toast notifications
- **Success:** Subtle toast, not intrusive
- **Transitions:** 150-200ms, ease-out curves
`
  };
}

function generateMVPScope(ctx: SoftwareProductContext): PRDSection {
  const mvpFeatures = (ctx.coreFeatures || []).slice(0, 4);
  
  return {
    title: '10. MVP Scope Definition',
    content: `### MVP Philosophy
**"Build the smallest thing that delivers real value."**

The MVP should:
- Solve ONE core problem completely
- Be usable by real users from day one
- Provide clear value within 5 minutes
- Be stable and secure (not hacky)

### What's IN the MVP
${mvpFeatures.map((f, i) => `${i + 1}. **${f}** - Essential for core value`).join('\n')}

### What's OUT of MVP (Phase 2+)
- Advanced analytics/reporting
- Team/collaboration features
- API for third-party integrations
- Mobile native apps (start with responsive web)
- Advanced customization options

### MVP Timeline Estimate
| Phase | Duration | Deliverable |
|-------|----------|-------------|
| Design | 1-2 days | Wireframes, component library |
| Core Backend | 2-3 days | Auth, database, core API |
| Core Frontend | 3-5 days | Main features, responsive UI |
| Polish | 2-3 days | Edge cases, loading states, testing |
| Launch Prep | 1-2 days | Deploy, monitoring, docs |
| **Total** | **9-15 days** | **Working MVP** |

### Definition of Done (MVP)
- [ ] Core feature fully functional
- [ ] User can complete primary use case end-to-end
- [ ] Authentication working securely
- [ ] Responsive on mobile and desktop
- [ ] Error handling for common cases
- [ ] Basic analytics/tracking in place
- [ ] Deployed to production URL
- [ ] Basic documentation written
`
  };
}

function generateSuccessMetrics(ctx: SoftwareProductContext): PRDSection {
  return {
    title: '11. Success Metrics & KPIs',
    content: `### North Star Metric
**Weekly Active Users (WAU)** who complete at least one [core action]

### Key Performance Indicators

#### Acquisition Metrics
- Website visitors → Signup conversion rate (target: >5%)
- Cost per acquisition (CPA)
- Traffic sources breakdown

#### Activation Metrics
- Time to first value (target: <5 minutes)
- Onboarding completion rate (target: >70%)
- Feature discovery rate

#### Engagement Metrics
- Daily/Weekly/Monthly Active Users
- Session duration
- Feature usage frequency
- Return visit rate

#### Retention Metrics
- Day 1, Day 7, Day 30 retention
- Churn rate
- Net Promoter Score (NPS)

#### Revenue Metrics (if applicable)
- Monthly Recurring Revenue (MRR)
- Average Revenue Per User (ARPU)
- Conversion rate (free → paid)
- Customer Lifetime Value (LTV)

### Success Criteria for MVP Launch
| Metric | 30-Day Target |
|--------|---------------|
| Signups | 100+ |
| Activation rate | >50% |
| D7 retention | >20% |
| NPS | >30 |
`
  };
}

function generateRisksAndMitigations(ctx: SoftwareProductContext): PRDSection {
  return {
    title: '12. Risks & Mitigations',
    content: `### Technical Risks
| Risk | Probability | Impact | Mitigation |
|------|-------------|--------|------------|
| Scope creep | High | High | Strict MVP definition, weekly review |
| Performance issues | Medium | High | Performance budget, monitoring |
| Security vulnerabilities | Medium | Critical | Security audit, best practices |
| Third-party API changes | Low | Medium | Abstract integrations, fallbacks |

### Market Risks
| Risk | Probability | Impact | Mitigation |
|------|-------------|--------|------------|
| Low user adoption | Medium | High | Early user feedback, iterate fast |
| Competitor releases similar | Medium | Medium | Focus on UVZ differentiators |
| Market timing wrong | Low | High | Validate demand before building |

### Operational Risks
| Risk | Probability | Impact | Mitigation |
|------|-------------|--------|------------|
| Key resource unavailable | Medium | High | Documentation, no single points of failure |
| Infrastructure costs spike | Low | Medium | Cost monitoring, usage limits |
| Support overwhelm | Low | Medium | Self-service docs, FAQ, community |

### Contingency Plans
1. **If adoption is low:** Pivot messaging, try different channels, interview churned users
2. **If tech debt accumulates:** Schedule refactoring sprints, prioritize stability
3. **If costs exceed budget:** Implement usage tiers, optimize infrastructure
`
  };
}

// Helper function to get default tech stack based on tool type
function getDefaultTechStack(toolType: string): string[] {
  const stacks: Record<string, string[]> = {
    'Chrome Extension': ['TypeScript', 'React', 'Manifest V3', 'Tailwind CSS', 'Vite'],
    'Firefox Extension': ['TypeScript', 'React', 'WebExtensions API', 'Tailwind CSS'],
    'VS Code Extension': ['TypeScript', 'VS Code API', 'esbuild'],
    'Desktop App (Electron)': ['TypeScript', 'React', 'Electron', 'Tailwind CSS', 'SQLite'],
    'CLI Tool': ['TypeScript', 'Node.js', 'Commander.js', 'Chalk'],
    'API/Service': ['TypeScript', 'Node.js', 'Express/Fastify', 'PostgreSQL', 'Redis'],
    'Figma Plugin': ['TypeScript', 'Figma Plugin API', 'React'],
    'Slack App': ['TypeScript', 'Bolt.js', 'Node.js', 'PostgreSQL'],
    'Web App': ['Next.js 14', 'React', 'TypeScript', 'Tailwind CSS', 'PostgreSQL', 'Prisma'],
    'Mobile App': ['React Native', 'Expo', 'TypeScript', 'PostgreSQL', 'Node.js'],
    'default': ['Next.js 14', 'React', 'TypeScript', 'Tailwind CSS', 'PostgreSQL', 'Prisma'],
  };
  
  return stacks[toolType] || stacks['default'];
}

// Export the main prompt generator
export function generateSoftwareBuildPrompt(context: SoftwareProductContext): string {
  const techStack = context.techStack || getDefaultTechStack(context.toolType);
  
  return `# ${context.name} - Complete Build Specification

You are a senior full-stack developer with 15+ years of experience building production-grade software. You will build a complete, professional ${context.toolType} following modern best practices.

## 🎯 PROJECT OVERVIEW

**Product:** ${context.name}
${context.tagline ? `**Tagline:** "${context.tagline}"` : ''}
**Type:** ${context.toolType}
**Problem:** ${context.problemSolved}

${context.uvz ? `### Unique Value Zone
${context.uvz}

This is what makes us different - keep this in mind for all design decisions.
` : ''}

${context.targetAudience ? `### Target Users
${context.targetAudience}
` : ''}

---

## ⚡ CORE FEATURES TO BUILD

${(context.coreFeatures || ['Core functionality']).map((f, i) => `### ${i + 1}. ${f}
- Implement complete functionality
- Include proper error handling
- Add loading and empty states
- Ensure responsive design
- Write clean, maintainable code
`).join('\n')}

---

## 🛠️ TECHNICAL REQUIREMENTS

### Tech Stack
${techStack.map(t => `- ${t}`).join('\n')}

### Code Quality Standards
- TypeScript strict mode enabled
- ESLint + Prettier configured
- Consistent naming conventions (camelCase for variables, PascalCase for components)
- Component-based architecture
- Separation of concerns (UI, business logic, data)
- No "any" types unless absolutely necessary
- Meaningful variable and function names
- Comments for complex logic only

### Architecture Principles
- Server components where possible (Next.js)
- Client components only when needed (interactivity)
- API routes for backend logic
- Environment variables for configuration
- No hardcoded secrets or URLs

---

## 🎨 UI/UX REQUIREMENTS

### Design Philosophy
**Professional and trustworthy, not flashy or gimmicky.**

### Visual Guidelines
- Clean, generous whitespace
- Clear visual hierarchy
- Consistent spacing (8px base unit)
- Rounded corners (8-12px)
- Subtle shadows for depth
- Color palette: Professional blues/grays with one accent color
- Typography: Inter or system fonts, clear hierarchy
- Icons: Lucide React or similar professional icon set

### Component Patterns
- Loading: Skeleton screens (not spinners)
- Empty states: Helpful message + illustration + CTA
- Errors: Inline validation + toast notifications
- Success: Subtle confirmation, not intrusive
- Buttons: Clear hierarchy (primary, secondary, ghost)
- Forms: Proper labels, validation feedback, accessible

### Responsive Breakpoints
- Mobile first approach
- sm: 640px, md: 768px, lg: 1024px, xl: 1280px

---

## 🔐 SECURITY REQUIREMENTS

### Authentication
- Secure password hashing (bcrypt, cost 12+)
- JWT with short expiry (15 min access token)
- Secure, httpOnly, sameSite cookies
- Rate limiting on auth endpoints

### Data Security
- Input validation on ALL user inputs (use Zod)
- Parameterized queries (no raw SQL)
- Output encoding to prevent XSS
- CSRF tokens for state-changing operations

### Headers
Add these security headers:
\`\`\`
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
Referrer-Policy: strict-origin-when-cross-origin
\`\`\`

---

## 📁 PROJECT STRUCTURE

\`\`\`
├── app/                    # Next.js app directory
│   ├── (auth)/            # Auth routes (login, signup)
│   ├── (dashboard)/       # Protected routes
│   ├── api/               # API routes
│   └── layout.tsx         # Root layout
├── components/
│   ├── ui/                # Reusable UI components
│   ├── forms/             # Form components
│   └── [feature]/         # Feature-specific components
├── lib/
│   ├── db.ts              # Database client
│   ├── auth.ts            # Auth utilities
│   ├── utils.ts           # Helper functions
│   └── validations.ts     # Zod schemas
├── hooks/                 # Custom React hooks
├── types/                 # TypeScript types
├── styles/                # Global styles
└── public/                # Static assets
\`\`\`

---

## 🚀 DELIVERABLES

1. **Complete working application** with all features
2. **Clean, documented code** following best practices
3. **Responsive UI** that works on mobile and desktop
4. **Secure authentication** system
5. **Database schema** with proper relations
6. **Error handling** for common edge cases
7. **Environment configuration** example (.env.example)

---

## ⚠️ IMPORTANT REMINDERS

1. **No placeholder code** - Everything should work
2. **No "TODO" comments** - Implement fully
3. **No console.logs in production code** - Use proper logging
4. **Handle all error states** - Don't assume happy path
5. **Mobile responsive** - Test all breakpoints
6. **Accessible** - Keyboard navigation, ARIA labels
7. **Performance** - Lazy load, optimize images, minimize bundle

Begin implementation now. Start with the project structure and core components.
`;
}

// Quick reference prompts for specific AI tools
export function generateToolSpecificPrompt(context: SoftwareProductContext, tool: string): string {
  const basePrompt = generateSoftwareBuildPrompt(context);
  
  const toolInstructions: Record<string, string> = {
    'lovable': `
## LOVABLE-SPECIFIC INSTRUCTIONS

Use Lovable's built-in features:
- Use their component library for UI
- Leverage their database integration
- Use their auth system
- Deploy using their hosting

Start by creating a new project and describe:
`,
    'bolt': `
## BOLT.NEW-SPECIFIC INSTRUCTIONS

Bolt works best with:
- Single file context initially
- Clear feature descriptions
- Iterative development
- Use /chat to refine

Paste this prompt and iterate:
`,
    'v0': `
## V0-SPECIFIC INSTRUCTIONS

V0 excels at UI components. Use it for:
- Generate individual components
- Create page layouts
- Build design system
- Then integrate into your project

Start with UI components:
`,
    'cursor': `
## CURSOR-SPECIFIC INSTRUCTIONS

Use Cursor's features:
- @codebase for context
- @docs to reference documentation
- Composer for multi-file edits
- Tab completion for speed

Create files in order:
1. package.json and configs
2. Database schema
3. API routes
4. Components
5. Pages
`,
    'replit': `
## REPLIT-SPECIFIC INSTRUCTIONS

Replit Agent works best with:
- Clear project description
- Feature list
- Let it scaffold the project
- Iterate on specific features

Start a new project and describe:
`,
    'claude': `
## CLAUDE-SPECIFIC INSTRUCTIONS

For Claude/Claude Code:
- Use Projects to maintain context
- Create artifacts for code files
- Ask for explanations when needed
- Iterate on specific parts

Start with architecture, then implement:
`,
  };
  
  const toolGuide = toolInstructions[tool.toLowerCase()] || '';
  
  return `${toolGuide}

${basePrompt}`;
}
